# Generated by Django 4.1.7 on 2023-03-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_author_alter_question_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='polls.tag'),
        ),
    ]
